### ISSUE TITLE
I get some error

### ISSUE THREAD

**Issue by pishguy** [xenoken/hermes#3]
I'm trying to use this library on Flutter , after downloading source code i get this errors:

> error: The final variable '' must be initialized. (final_not_initialized src\hermes_base.dart:13)
> error: Expected to find ';'. (expected_token at [cheetah] src\hermes_base.dart:13)
> error: Expected an identifier. (missing_identifier src\hermes_base.dart:13)
> error: The method 'add' isn't defined for the class 'Hermes'. (src\hermes_base.dart:13)
> error: The final variable '' must be initialized. (final_not_initialized src\hermes_base.dart:14)
> error: The name '' is already defined. (duplicate_definition src\hermes_base.dart:14)
> error: Expected to find ';'. (expected_token at src\hermes_base.dart:14)
> error: Expected an identifier. (missing_identifier at [cheetah] src\hermes_base.dart:14)
> error: Expected to find ';'. (expected_token at src\hermes_base.dart:14)
> error: Expected an identifier. (missing_identifier src\hermes_base.dart:14)

**Comment by xenoken** [comment]
Hey @MahdiPishguy, thank you for your interest in Hermes!.
Could you please give me more information about your problem? Did you download the source code from Github directly?
Have you tried to add Hermes as a dependency in your pubspec.yaml in your Flutter project?

**Comment by pishguy** [comment]
@xenoken i used only source code on github and i don't try to add the library in  `pubspec.yaml`

i can't find how can i add it to the file. its not in library readme

**Comment by pishguy** [comment]
i found it in dart packages

hermes: ^3.0.0

Thanks
